name: "setup-katoa"
description: "Setup Katoa"
branding:
  icon: "arrow-right-circle"
  color: "purple"
runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: curl -fSsL https://raw.githubusercontent.com/katoahq/katoa/main/download.sh | sh
      shell: bash
