name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Katoa
        uses: ./

      - name: Katoa Version
        run: katoa -V

      - name: Katoa init
        run: katoa init pipeline

      - name: Katoa run
        run: katoa run .katoa/pipeline.ts
